version: '3.7'
services:
  php:
    image: bscheshir/php:7.4.3-fpm-alpine-4yii2
    restart: always
    volumes:
      - ./php-data:/var/www/html #php-data
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: "${TZ}"
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    expose:
      - "${NGINX_FRONTEND_PORT}:8080"
      - "${NGINX_BACKEND_PORT}:8081"
#    ports: # use nginx-proxy in same network (see ./docs/nginx-proxy.md)
#      - "8080:8080"
#      - "8081:8081"
    depends_on:
      - php
    volumes:
      - ../php-data:/var/www/html #php-data
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
    environment:
      TZ: "${TZ}"
  db:
    image: mysql:8.0.19
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password' # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
