version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: ../Dockerfile
      args:
        PHP_BASE_IMAGE_VERSION: "bscheshir/php:7.4.3-fpm-alpine-4yii2-xdebug"
    restart: always
    volumes:
      - ../php-data:/var/www/html #php-data
      - ~/.composer/cache:/root/.composer/cache
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      TZ: "${TZ}"
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT} remote_enable=On var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME}"
  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    expose:
      - "80"
    depends_on:
      - php
    volumes:
      - ../php-data:/var/www/html #php-data
      - ../nginx-conf-test:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
    networks:
      default:
        aliases:
         - backend.dev
         - frontend.dev
         - storage.dev
    environment:
      TZ: "${TZ}"
  db:
    image: mysql:8.0.19
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password' # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3006"
    volumes:
      - ../mysql-data-test/db:/var/lib/mysql #mysql-data
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  codecept:
    image: bscheshir/codeception:php7.4.3-fpm-alpine-yii2
    depends_on:
      - nginx
      - browser
    volumes:
      - ../php-data:/var/www/html #php-data
    environment:
      TZ: "${TZ}"
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT_CODECEPTION} remote_enable=On"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME_CODECEPTION}"
  browser:
    image: selenium/standalone-chrome-debug:3.141.59
    depends_on:
      - nginx
    volumes:
      - /dev/shm:/dev/shm # the docker run instance may use the default 64MB, that may not be enough in some cases
    ports:
      - '${BROWSER_PUBLISH_PORT}:4444'
      - '${BROWSER_VNC_PORT}:5900'
    environment:
      TZ: "${TZ}"
