version: '3.7'
services:
  php:
    image: bscheshir/php:7.4.3-fpm-alpine-4yii2-xdebug
    restart: always
    volumes:
      - ../php-data:/var/www/html #php-data
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: "${TZ}"
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT} var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME}"
  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    ports:
      - "${NGINX_FRONTEND_PORT}:8080"
      - "${NGINX_BACKEND_PORT}:8081"
    depends_on:
      - php
    volumes:
      - ../php-data:/var/www/html #php-data
      - ../nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
    environment:
      TZ: "${TZ}"
  mysql:
    image: mysql:8.0.19
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password' # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    expose:
      - "${MYSQL_INTERNAL_PORT}" #for service mysql-proxy
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}" #for external connection
    volumes:
      - ../mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      VIRTUAL_PORT: "${MYSQL_INTERNAL_PORT}"
  db: #mysql-proxy
    image: bscheshir/mysql-proxy:0.8.5
    expose:
      - "${PROXY_DB_INTERNAL_PORT}" #for service php
    ports:
      - "${PROXY_DB_EXTERNAL_PORT}:${PROXY_DB_INTERNAL_PORT}" #for external connection
    restart: always
    volumes:
      - ../mysql-proxy-conf:/opt/mysql-proxy/conf
      - ../mysql-proxy-logs:/opt/mysql-proxy/logs
    depends_on:
      - mysql
    environment:
      TZ: "${TZ}"
      PROXY_DB_HOST: "${PROXY_DB_HOST}"
      PROXY_DB_PORT: "${PROXY_DB_INTERNAL_PORT}"
      REMOTE_DB_HOST: mysql
      REMOTE_DB_PORT: "${MYSQL_INTERNAL_PORT}"
      LUA_SCRIPT: "/opt/mysql-proxy/conf/log.lua"
      LOG_FILE: "/opt/mysql-proxy/logs/mysql.log"
